language: php

php:
  - 5.4
  - 5.5

before_script: 
  - cp app/config/parameters.test.yml app/config/parameters.yml
  - composer selfupdate
  - composer install --prefer-source
  - ./install-sphinx

script:
    - ./runtests sphinx
    - ./runtests