parameters:
#    acts_camdram.example.class: Acts\CamdramBundle\Example

services:
    camdram.security.encoder.legacy_md5:
        class:  Acts\CamdramSecurityBundle\Security\Encoder\LegacyMd5Encoder

    camdram.security.utils:
        class: Acts\CamdramSecurityBundle\Security\SecurityUtils
        arguments: [@service_container]

    camdram.security.name_utils:
        class: Acts\CamdramSecurityBundle\Security\NameUtils
        arguments: [@doctrine.orm.entity_manager]

    camdram.security.twig.extension:
        class: Acts\CamdramSecurityBundle\Twig\Extension\CamdramSecurityExtension
        arguments: [@camdram.security.utils]
        tags: [{ name: twig.extension }]

    camdram.security.authentication_success_handler:
        class: Acts\CamdramSecurityBundle\Security\Handler\AuthenticationSuccessHandler
        arguments: [@security.context, @camdram.security.name_utils, @camdram.security.user.provider, @camdram.security.external_user.provider, @camdram.security.user_linker, @security.http_utils, 'public']

    camdram.security.entry_point:
        class: Acts\CamdramSecurityBundle\Security\EntryPoint\CamdramLoginEntryPoint
        arguments: [@security.authentication.form_entry_point.public, @security.context]

    camdram.security.user_linker:
        class: Acts\CamdramSecurityBundle\Security\UserLinker
        arguments: [@doctrine.orm.entity_manager]

    camdram.security.type.graduation_year:
        class: Acts\CamdramSecurityBundle\Form\Type\GraduationYearType
        arguments: ~
        tags:
            - { name: form.type, alias: graduation_year }

    camdram.security.type.occupation:
        class: Acts\CamdramSecurityBundle\Form\Type\OccupationType
        arguments: ~
        tags:
            - { name: form.type, alias: occupation }

    camdram.security.acl.provider:
        class: Acts\CamdramSecurityBundle\Security\Acl\AclProvider
        arguments: [@doctrine.orm.entity_manager]

    camdram.security.acl.helper:
        class: Acts\CamdramSecurityBundle\Security\Acl\Helper
        arguments: [@security.context, @camdram.security.acl.provider]

    camdram.security.user.provider:
        class: Acts\CamdramSecurityBundle\Security\User\CamdramUserProvider
        arguments: [@doctrine.orm.entity_manager]

    camdram.security.external_user.provider:
        class: Acts\CamdramSecurityBundle\Security\User\ExternalLoginUserProvider
        arguments: [@doctrine.orm.entity_manager]

    camdram.security.token_generator:
        class: Acts\CamdramSecurityBundle\Service\TokenGenerator
        arguments: [%secret%]

    camdram.security.email_send_listener:
        class: Acts\CamdramSecurityBundle\EventListener\EmailSendListener
        arguments: [@camdram.security.email_dispatcher, @camdram.security.token_generator]
        tags:
            - { name: kernel.event_listener, event: camdram_security.registration_complete, method: onRegistrationEvent }
            - { name: kernel.event_listener, event: camdram_security.pending_acccess_created, method: onPendingAccessCreatedEvent }

    camdram.security.listener.pending_access:
        class: Acts\CamdramSecurityBundle\EventListener\PendingAccessListener
        arguments: [@camdram.security.email_dispatcher]
        tags:
            - { name: doctrine.entity_listener }

    camdram.security.listener.user:
        class: Acts\CamdramSecurityBundle\EventListener\UserListener
        arguments: [@camdram.security.email_dispatcher, @camdram.security.token_generator]
        tags:
            - { name: doctrine.entity_listener }

    camdram.security.email_dispatcher:
        class: Acts\CamdramSecurityBundle\Service\EmailDispatcher
        arguments: [@doctrine.orm.entity_manager, @swiftmailer.mailer, @twig, %mailer_sender_address%]

    ### Authorization voters

    camdram.security.voter.create:
        class: Acts\CamdramSecurityBundle\Security\Acl\Voter\CreateVoter
        tags:
            - { name: security.voter }

    camdram.security.voter.admin:
        class: Acts\CamdramSecurityBundle\Security\Acl\Voter\AdminVoter
        tags:
            - { name: security.voter }

    camdram.security.voter.editor:
        class: Acts\CamdramSecurityBundle\Security\Acl\Voter\EditorVoter
        tags:
            - { name: security.voter }

    camdram.security.voter.owner:
        class: Acts\CamdramSecurityBundle\Security\Acl\Voter\OwnerVoter
        arguments: [@camdram.security.acl.provider]
        tags:
            - { name: security.voter }

    camdram.security.voter.show:
        class: Acts\CamdramSecurityBundle\Security\Acl\Voter\ShowVoter
        arguments: [@camdram.security.acl.provider]
        tags:
            - { name: security.voter }

    camdram.security.voter.profile:
        class: Acts\CamdramSecurityBundle\Security\Acl\Voter\ProfileVoter
        tags:
            - { name: security.voter }

    camdram.security.voter.view:
        class: Acts\CamdramSecurityBundle\Security\Acl\Voter\ViewVoter
        tags:
            - { name: security.voter }

