parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     camdram_test
    database_user:     root
    database_pass:     password

    search_namespace: camdram_mysql
    search_enable_listeners: true
