parameters:
    database_driver:   pdo_sqlite
    database_host:     localhost
    database_port:     ~
    database_name_orm:     ~
    database_user_orm:     ~
    database_pass_orm:     ~
    database_name_odm:     ~
    database_user_odm:     ~
    database_pass_odm:     ~

    # PHPCD-ODM Settings
    phpcr_backend:
        type: doctrinedbal
        connection: odm
    phpcr_workspace: default
    phpcr_user: admin
    phpcr_pass: admin

    # During development send emails from your own gmail address e.g.
    # your_username@gmail.com.
    mailer_transport:  gmail
    mailer_host:       ~
    mailer_user:       your_gmail_username
    mailer_password:   your_gmail_password
    mailer_delivery_address: example@example.com
    mailer_sender_address    : websupport@camdram.net

    locale:            en
    secret:            "default secret"

    facebook_id:                1234
    facebook_secret:            s3cr3t
    twitter_key:                1234
    twitter_secret:             s3cr3t
    twitter_token:              1234
    twitter_token_secret:       s3cr3t
    google_client_id:           1234
    google_client_secret:       s3cr3t
    google_key:                 s3cr3t
    github_id:                  1234
    github_secret:              s3cr3t

    baseurl: http://www.camdram.net

    map_center: [52.20531,0.12179]
    search_provider: doctrine
    term_dates_ical: http://www.google.com/calendar/ical/cam.ac.uk_t5c3ocr5f5ehr8ln3ec4ile1g0%40group.calendar.google.com/public/basic.ics

    ruby_bin: /usr/bin/ruby
    ruby_bin_dir: /usr/local/bin
    node_bin_dir: /usr/local/bin
