acts_camdram_api:
    resource: "@ActsCamdramApiBundle/Resources/config/routing.yml"
    prefix:   /api

acts_external_login:
    resource: "@ActsExternalLoginBundle/Resources/config/routing.yml"
    prefix:   /extauth

acts_camdram_backend:
    resource: "@ActsCamdramBackendBundle/Resources/config/routing.yml"
    prefix:   /

acts_camdram:
    resource: "@ActsCamdramBundle/Resources/config/routing.yml"
    prefix:   /

acts_camdram_legacy:
    resource: "@ActsCamdramLegacyBundle/Resources/config/routing.yml"
    prefix:   /legacy

acts_camdram_security:
    resource: "@ActsCamdramSecurityBundle/Resources/config/routing.yml"
    prefix:   /auth
    schemes:  [https]

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
_security_check:
      pattern:  /login_check
_security_logout:
      pattern:  /logout

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

hoyes_image_manager_bundle:
    resource: "@HoyesImageManagerBundle/Resources/config/routing.yml"
    prefix: /images

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"