security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_EDITOR]
        ROLE_EDITOR:      [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class: Acts\CamdramSecurityBundle\Entity\User
                property: email
        external_login:
            id: camdram.security.external_user.provider

    firewalls:
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        public:
            pattern: ^/.*
            anonymous: true
            switch_user: { role: ROLE_ADMIN, parameter: _switch_to_user }
            entry_point: camdram.security.entry_point
            fos_oauth: true
            logout:
                path: /logout
                target: /
            form_login:
                check_path: /auth/login_check
                login_path: /auth/login
                username_parameter: email
                password_parameter: password
                success_handler:  camdram.security.authentication_success_handler
            external_login:
                services: [raven, facebook, google]
                success_handler:  camdram.security.authentication_success_handler
            remember_me:
                key:      %secret%
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
#        - { path ^/.*\.(json|xml)$, roles: ROLE_API }
        - { path ^/auth/settings.*, roles: IS_AUTHENTICATED_FULLY }

    encoders:
        Acts\CamdramSecurityBundle\Entity\User:
            id: camdram.security.encoder.legacy_md5

acts_external_login:
    user_provider_id: camdram.security.external_user.provider
    services:
        facebook:
            class: social_api
            settings:
                api: facebook
        google:
            class: social_api
            settings:
                api: google
        raven:
            class: raven
            settings:
                description: "camdram.net"