security:

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_EDITOR]
        ROLE_EDITOR:      [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity:
                class: Acts\CamdramSecurityBundle\Entity\User
                property: email

    firewalls:
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        public:
            pattern: ^/.*
            anonymous: true
            switch_user: { role: ROLE_ADMIN, parameter: _switch_to_user }
            fos_oauth: true
            logout:
                path: /logout
                target: /
            form_login:
                check_path: /auth/login_check
                login_path: /auth/login
                username_parameter: email
                password_parameter: password
            oauth:
                resource_owners:
                    raven:              "/auth/check-raven"
                    facebook:           "/auth/oauth/check-facebook"
                    google:             "/auth/oauth/check-google"
                    twitter:            "/auth/oauth/check-twitter"
                login_path:        /auth/login
                use_forward:       false
                failure_path:      /auth/login
                oauth_user_provider:
                    service: camdram.security.user.provider
            
                login_path: "/auth/login"
            remember_me:
                secret:      %secret%
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~
                always_remember_me: true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
#        - { path ^/.*\.(json|xml)$, roles: ROLE_API }

    encoders:
        Acts\CamdramSecurityBundle\Entity\User:
            id: camdram.security.encoder.legacy_md5

hwi_oauth:
    firewall_names: [public]
    grant_rule: 'IS_AUTHENTICATED_FULLY'
    target_path_parameter: _destination
    connect:
        account_connector: camdram.security.user.provider
        registration_form: camdram.security.registration.form
        registration_form_handler: camdram.security.registration.handler
    resource_owners:
        facebook:
            type: facebook
            client_id: %facebook_id%
            client_secret: %facebook_secret%
            scope: "email user_friends"
            options:
                csrf: true
        google:
            type: google
            client_id: %google_client_id%
            client_secret: %google_client_secret%
            scope: "email profile"
            options:
                csrf: true
        twitter:
            type: twitter
            client_id: %twitter_key%
            client_secret: %twitter_secret%
            options:
                csrf: true
                include_email: true
        raven:
            service: "camdram.security.raven.resource_owner"