parameters:
    acts_camdram_backend.database_tools.class: Acts\CamdramBackendBundle\Service\DatabaseTools
    assetic.filter.scssphp.class: Acts\CamdramBackendBundle\Service\ScssphpFilter

services:
    acts_camdram_backend.database_tools:
        class: %acts_camdram_backend.database_tools.class%
        arguments: [@doctrine.orm.entity_manager]

    acts_camdram_backend.log_procesor:
        class: Acts\CamdramBackendBundle\Logger\LogProcessor
        arguments:  [@service_container]
        tags:
            - { name: monolog.processor, method: processRecord, channel: camdram }

    acts_camdram_backend.doctrine.entity_listener_resolver:
        class: Acts\CamdramBackendBundle\Doctrine\EntityListenerResolver
        arguments: [@service_container]
