parameters:
    acts.diary.factory.class: Acts\DiaryBundle\Diary\DiaryFactory
    acts.diary.renderer.html.class: Acts\DiaryBundle\Diary\Renderer\HtmlRenderer
    acts.diary.twig_extension.class: Acts\DiaryBundle\Twig\DiaryExtension

services:
    acts.diary.factory:
        class: %acts.diary.factory.class%

    acts.diary.renderer.html:
        class: %acts.diary.renderer.html.class%
        arguments: ['@twig']

    acts.diary.twig_extension:
        class: %acts.diary.twig_extension.class%
        tags:
            - { name: twig.extension }
